/**
 * 110+ dish name templates (Dutch/English), grouped by category key.
 */
export const dishNamesByCategory: Record<string, string[]> = {
  Pizza: [
    "Margherita Classica",
    "Quattro Formaggi",
    "Capricciosa",
    "Diavola",
    "Prosciutto e Rucola",
    "Truffel Burrata",
    "Nduja & honing",
    "Veggie Deluxe",
    "Fungi Porcini",
    "Cacio e pepe",
  ],
  Sushi: [
    "Sashimi trio",
    "Nigiri chef's selectie",
    "Spicy tunaroll",
    "Dragon uramaki",
    "Sake avocado roll",
    "Temaki zalm",
    "Chirashi bowl",
    "Yellowtail tataki",
    "Ebi tempura maki",
    "Omakase 12 stukken",
  ],
  Burgers: [
    "Smash double",
    "Blue cheese burger",
    "Fried chicken burger",
    "BBQ onion burger",
    "Vegan beyond burger",
    "Truffel mayonaise",
    "Koreaanse gochujang",
    "Classic cheese",
    "Jalapeño & bacon",
    "Halloumi & avocado",
  ],
  Pasta: [
    "Cacio e pepe",
    "Pappardelle ragù",
    "Gnocchi burro salvia",
    "Linguine vongole",
    "Lasagna tradizionale",
    "Pesto Genovese",
    "Aglio olio e peperoncino",
    "Ossobuco pappardelle",
    "Spaghetti amatriciana",
    "Tortellini brodo",
  ],
  Ramen: [
    "Tonkotsu ramen",
    "Miso chashu",
    "Shoyu tori",
    "Tantanmen pittig",
    "Tsukemen dippen",
    "Karaage bento",
    "Katsu curry rice",
    "Poke bowl tonijn",
    "Gyu don",
    "Yakitori set",
  ],
  Tacos: [
    "Carnitas taco (3st)",
    "Baja vis taco",
    "Mushroom el pastor",
    "Barbacoa taco's",
    "Ceviche tostada's",
    "Gegrilde mais burrito",
    "Quesadilla mix",
    "Nacho's met guac",
    "Birria taco's",
    "Frijoles bowl",
  ],
  Ontbijt: [
    "Eggs benedict",
    "Açai power bowl",
    "Amsterdamse flensjes",
    "Croque madame",
    "Avocado & za'atar toast",
    "Frittata groente",
    "Bircher muesli",
    "Griekse yoghurt pannenkoeken",
    "Bacon stack & maple",
    "Matcha overnight oats",
  ],
  Salade: [
    "Caesar met kip",
    "Burrata & peer",
    "Falafel fattoush",
    "Quinoa rainbow bowl",
    "Gegrilde zalm nicoise",
    "Cobb salad",
    "Caprese burrata",
    "Gado gado",
    "Thaise papaya",
    "Spelt en geitenkaas",
  ],
  Steak: [
    "Biefstuk 250g",
    "Côte de bœuf voor twee",
    "Entrecôte chimichurri",
    "Bavette met friet",
    "Duck magret sinaasappel",
    "Kalfs ribeye",
    "Hanger steak",
    "Surf & turf",
    "Dry-aged prime rib",
    "Bief carpaccio",
  ],
  Indisch: [
    "Butter chicken & naan",
    "Paneer tikka",
    "Kerala vis curry",
    "Biryani lam",
    "Masala dosa",
    "Kofta curry",
    "Palak met paneer",
    "Vindaloo pittig",
    "Kachumber salade & dal",
    "Gulab jamun dessert",
  ],
  Midden: [
    "Mezze voor twee",
    "Falafel pita",
    "Shakshuka",
    "Adana spies",
    "Baba ghanoush platter",
    "Fattet hummus",
    "Grill mix met rijst",
    "Fisherman's tagine",
    "Baklava assorti",
    "Fattoush shawarma",
  ],
  Aziatisch: [
    "Pad thai jumbo garnalen",
    "Bao's trio",
    "Vietnamese pho",
    "Banh mi gegrild",
    "Dumpling basket",
    "Geroosterde eend rijst",
    "Gember zalm tataki",
    "Teriyaki bowl",
    "Gochujang fried chicken",
    "Coconut soep",
  ],
};

export const imagePool = [
  "/dishes/01-grilled-tosti.png",
  "/dishes/02-empanadas.png",
  "/dishes/03-friet.png",
  "/dishes/04-fish-tacos.png",
  "/dishes/05-sushi-platter.png",
  "/dishes/06-paneer-masala.png",
  "/dishes/07-beef-pide.png",
  "/dishes/08-loaded-satay.png",
  "/dishes/09-saag-paneer.png",
  "/dishes/10-shrimp-tacos.png",
  "/dishes/11-butter-chicken.png",
  "/dishes/12-beef-medallions.png",
  "/dishes/13-hariyali-tikka.png",
  "/dishes/14-fruitbord.png",
  "/dishes/15-fettuccine.png",
  "/dishes/16-flatbread-naan.png",
  "/dishes/17-loempia.png",
  "/dishes/18-pizza-margherita.png",
  "/dishes/19-loaded-hotdog.png",
  "/dishes/20-couscous-bowl.png",
  "/dishes/21-arancini-platter.png",
  "/dishes/22-honey-cake.png",
  "/dishes/23-paneer-masala-2.png",
];

/**
 * 23 explicit dishes with their assigned local photo, dish name, and category.
 * These are seeded first — the rest of the pool fills up to TARGET_DISHES.
 */
export const photoDishes: {
  image: string;
  name: string;
  category: string;
}[] = [
  { image: "/dishes/01-grilled-tosti.png", name: "Croque Monsieur", category: "Ontbijt" },
  { image: "/dishes/02-empanadas.png", name: "Empanadas de Carne", category: "Tacos" },
  { image: "/dishes/03-friet.png", name: "Friet Speciaal", category: "Burgers" },
  { image: "/dishes/04-fish-tacos.png", name: "Baja Fish Tacos", category: "Tacos" },
  { image: "/dishes/05-sushi-platter.png", name: "Sashimi Platter", category: "Sushi" },
  { image: "/dishes/06-paneer-masala.png", name: "Paneer Tikka Masala", category: "Indisch" },
  { image: "/dishes/07-beef-pide.png", name: "Turkse Pide met Rund", category: "Midden" },
  { image: "/dishes/08-loaded-satay.png", name: "Loaded Satay Fries", category: "Aziatisch" },
  { image: "/dishes/09-saag-paneer.png", name: "Saag Paneer", category: "Indisch" },
  { image: "/dishes/10-shrimp-tacos.png", name: "Shrimp Tacos", category: "Tacos" },
  { image: "/dishes/11-butter-chicken.png", name: "Butter Chicken & Naan", category: "Indisch" },
  { image: "/dishes/12-beef-medallions.png", name: "Biefstuk Medaillons", category: "Steak" },
  { image: "/dishes/13-hariyali-tikka.png", name: "Hariyali Tikka", category: "Indisch" },
  { image: "/dishes/14-fruitbord.png", name: "Vers Fruitbord", category: "Salade" },
  { image: "/dishes/15-fettuccine.png", name: "Fettuccine Alfredo", category: "Pasta" },
  { image: "/dishes/16-flatbread-naan.png", name: "Garlic Naan & Dips", category: "Indisch" },
  { image: "/dishes/17-loempia.png", name: "Vietnamese Loempia's", category: "Aziatisch" },
  { image: "/dishes/18-pizza-margherita.png", name: "Pizza Margherita", category: "Pizza" },
  { image: "/dishes/19-loaded-hotdog.png", name: "Loaded Hotdog", category: "Burgers" },
  { image: "/dishes/20-couscous-bowl.png", name: "Couscous Bowl", category: "Midden" },
  { image: "/dishes/21-arancini-platter.png", name: "Arancini Trio", category: "Pasta" },
  { image: "/dishes/22-honey-cake.png", name: "Honey Layer Cake", category: "Ontbijt" },
  { image: "/dishes/23-paneer-masala-2.png", name: "Kadhai Paneer", category: "Indisch" },
];
